/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.FootballClassificationEntry;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChGroupClassificationEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class ChGroupClassificationEntry {
  @SerializedName("group")
  private Integer group = null;

  @SerializedName("entries")
  private List<FootballClassificationEntry> entries = null;

  public ChGroupClassificationEntry group(Integer group) {
    this.group = group;
    return this;
  }

   /**
   * Number of group
   * @return group
  **/
  @ApiModelProperty(value = "Number of group")
  public Integer getGroup() {
    return group;
  }

  public void setGroup(Integer group) {
    this.group = group;
  }

  public ChGroupClassificationEntry entries(List<FootballClassificationEntry> entries) {
    this.entries = entries;
    return this;
  }

  public ChGroupClassificationEntry addEntriesItem(FootballClassificationEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<FootballClassificationEntry>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(value = "")
  public List<FootballClassificationEntry> getEntries() {
    return entries;
  }

  public void setEntries(List<FootballClassificationEntry> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChGroupClassificationEntry chGroupClassificationEntry = (ChGroupClassificationEntry) o;
    return Objects.equals(this.group, chGroupClassificationEntry.group) &&
        Objects.equals(this.entries, chGroupClassificationEntry.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChGroupClassificationEntry {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

