/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.ChResultStat;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a match result
 */
@ApiModel(description = "Represents a match result")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class ChKnockoutMatchDayStats {
  @SerializedName("championId")
  private Long championId = null;

  @SerializedName("matchDay")
  private Integer matchDay = null;

  @SerializedName("weekDay")
  private Integer weekDay = null;

  @SerializedName("legOrder")
  private Integer legOrder = null;

  @SerializedName("eventTime")
  private OffsetDateTime eventTime = null;

  @SerializedName("results")
  private List<ChResultStat> results = null;

  public ChKnockoutMatchDayStats championId(Long championId) {
    this.championId = championId;
    return this;
  }

   /**
   * Get championId
   * @return championId
  **/
  @ApiModelProperty(value = "")
  public Long getChampionId() {
    return championId;
  }

  public void setChampionId(Long championId) {
    this.championId = championId;
  }

  public ChKnockoutMatchDayStats matchDay(Integer matchDay) {
    this.matchDay = matchDay;
    return this;
  }

   /**
   * Get matchDay
   * @return matchDay
  **/
  @ApiModelProperty(value = "")
  public Integer getMatchDay() {
    return matchDay;
  }

  public void setMatchDay(Integer matchDay) {
    this.matchDay = matchDay;
  }

  public ChKnockoutMatchDayStats weekDay(Integer weekDay) {
    this.weekDay = weekDay;
    return this;
  }

   /**
   * Day of the matchday in which the match is played.  
   * @return weekDay
  **/
  @ApiModelProperty(value = "Day of the matchday in which the match is played.  ")
  public Integer getWeekDay() {
    return weekDay;
  }

  public void setWeekDay(Integer weekDay) {
    this.weekDay = weekDay;
  }

  public ChKnockoutMatchDayStats legOrder(Integer legOrder) {
    this.legOrder = legOrder;
    return this;
  }

   /**
   * Get legOrder
   * @return legOrder
  **/
  @ApiModelProperty(value = "")
  public Integer getLegOrder() {
    return legOrder;
  }

  public void setLegOrder(Integer legOrder) {
    this.legOrder = legOrder;
  }

  public ChKnockoutMatchDayStats eventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEventTime() {
    return eventTime;
  }

  public void setEventTime(OffsetDateTime eventTime) {
    this.eventTime = eventTime;
  }

  public ChKnockoutMatchDayStats results(List<ChResultStat> results) {
    this.results = results;
    return this;
  }

  public ChKnockoutMatchDayStats addResultsItem(ChResultStat resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<ChResultStat>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(value = "")
  public List<ChResultStat> getResults() {
    return results;
  }

  public void setResults(List<ChResultStat> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChKnockoutMatchDayStats chKnockoutMatchDayStats = (ChKnockoutMatchDayStats) o;
    return Objects.equals(this.championId, chKnockoutMatchDayStats.championId) &&
        Objects.equals(this.matchDay, chKnockoutMatchDayStats.matchDay) &&
        Objects.equals(this.weekDay, chKnockoutMatchDayStats.weekDay) &&
        Objects.equals(this.legOrder, chKnockoutMatchDayStats.legOrder) &&
        Objects.equals(this.eventTime, chKnockoutMatchDayStats.eventTime) &&
        Objects.equals(this.results, chKnockoutMatchDayStats.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(championId, matchDay, weekDay, legOrder, eventTime, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChKnockoutMatchDayStats {\n");
    
    sb.append("    championId: ").append(toIndentedString(championId)).append("\n");
    sb.append("    matchDay: ").append(toIndentedString(matchDay)).append("\n");
    sb.append("    weekDay: ").append(toIndentedString(weekDay)).append("\n");
    sb.append("    legOrder: ").append(toIndentedString(legOrder)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

