/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Object to define company contact information 
 */
@ApiModel(description = "Object to define company contact information ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class CompanyContactInfo {
  @SerializedName("name")
  private String name = null;

  @SerializedName("logoUrl")
  private String logoUrl = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("otherAddress")
  private String otherAddress = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("otherPhone")
  private String otherPhone = null;

  @SerializedName("fax")
  private String fax = null;

  @SerializedName("icqNumber")
  private String icqNumber = null;

  @SerializedName("skype")
  private String skype = null;

  @SerializedName("webSite")
  private String webSite = null;

  @SerializedName("regNumber")
  private String regNumber = null;

  @SerializedName("taxNumber")
  private String taxNumber = null;

  @SerializedName("vatNumber")
  private String vatNumber = null;

  public CompanyContactInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name 
   * @return name
  **/
  @ApiModelProperty(value = "Name ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CompanyContactInfo logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Logo image URL (Max. 1MB) 
   * @return logoUrl
  **/
  @ApiModelProperty(value = "Logo image URL (Max. 1MB) ")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public CompanyContactInfo address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Postal address 
   * @return address
  **/
  @ApiModelProperty(value = "Postal address ")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public CompanyContactInfo otherAddress(String otherAddress) {
    this.otherAddress = otherAddress;
    return this;
  }

   /**
   * Additional postal address 
   * @return otherAddress
  **/
  @ApiModelProperty(value = "Additional postal address ")
  public String getOtherAddress() {
    return otherAddress;
  }

  public void setOtherAddress(String otherAddress) {
    this.otherAddress = otherAddress;
  }

  public CompanyContactInfo postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal/ZIP code 
   * @return postalCode
  **/
  @ApiModelProperty(value = "Postal/ZIP code ")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public CompanyContactInfo city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City 
   * @return city
  **/
  @ApiModelProperty(value = "City ")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public CompanyContactInfo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country 
   * @return country
  **/
  @ApiModelProperty(value = "Country ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CompanyContactInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address 
   * @return email
  **/
  @ApiModelProperty(value = "Email address ")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CompanyContactInfo phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Phone number 
   * @return phone
  **/
  @ApiModelProperty(value = "Phone number ")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public CompanyContactInfo otherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
    return this;
  }

   /**
   * Additional phone number 
   * @return otherPhone
  **/
  @ApiModelProperty(value = "Additional phone number ")
  public String getOtherPhone() {
    return otherPhone;
  }

  public void setOtherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
  }

  public CompanyContactInfo fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Fax number 
   * @return fax
  **/
  @ApiModelProperty(value = "Fax number ")
  public String getFax() {
    return fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public CompanyContactInfo icqNumber(String icqNumber) {
    this.icqNumber = icqNumber;
    return this;
  }

   /**
   * ICQ number 
   * @return icqNumber
  **/
  @ApiModelProperty(value = "ICQ number ")
  public String getIcqNumber() {
    return icqNumber;
  }

  public void setIcqNumber(String icqNumber) {
    this.icqNumber = icqNumber;
  }

  public CompanyContactInfo skype(String skype) {
    this.skype = skype;
    return this;
  }

   /**
   * Skype username 
   * @return skype
  **/
  @ApiModelProperty(value = "Skype username ")
  public String getSkype() {
    return skype;
  }

  public void setSkype(String skype) {
    this.skype = skype;
  }

  public CompanyContactInfo webSite(String webSite) {
    this.webSite = webSite;
    return this;
  }

   /**
   * Web site URL 
   * @return webSite
  **/
  @ApiModelProperty(value = "Web site URL ")
  public String getWebSite() {
    return webSite;
  }

  public void setWebSite(String webSite) {
    this.webSite = webSite;
  }

  public CompanyContactInfo regNumber(String regNumber) {
    this.regNumber = regNumber;
    return this;
  }

   /**
   * Registration number 
   * @return regNumber
  **/
  @ApiModelProperty(value = "Registration number ")
  public String getRegNumber() {
    return regNumber;
  }

  public void setRegNumber(String regNumber) {
    this.regNumber = regNumber;
  }

  public CompanyContactInfo taxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
    return this;
  }

   /**
   * TAX number 
   * @return taxNumber
  **/
  @ApiModelProperty(value = "TAX number ")
  public String getTaxNumber() {
    return taxNumber;
  }

  public void setTaxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
  }

  public CompanyContactInfo vatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
    return this;
  }

   /**
   * VAT number 
   * @return vatNumber
  **/
  @ApiModelProperty(value = "VAT number ")
  public String getVatNumber() {
    return vatNumber;
  }

  public void setVatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyContactInfo companyContactInfo = (CompanyContactInfo) o;
    return Objects.equals(this.name, companyContactInfo.name) &&
        Objects.equals(this.logoUrl, companyContactInfo.logoUrl) &&
        Objects.equals(this.address, companyContactInfo.address) &&
        Objects.equals(this.otherAddress, companyContactInfo.otherAddress) &&
        Objects.equals(this.postalCode, companyContactInfo.postalCode) &&
        Objects.equals(this.city, companyContactInfo.city) &&
        Objects.equals(this.country, companyContactInfo.country) &&
        Objects.equals(this.email, companyContactInfo.email) &&
        Objects.equals(this.phone, companyContactInfo.phone) &&
        Objects.equals(this.otherPhone, companyContactInfo.otherPhone) &&
        Objects.equals(this.fax, companyContactInfo.fax) &&
        Objects.equals(this.icqNumber, companyContactInfo.icqNumber) &&
        Objects.equals(this.skype, companyContactInfo.skype) &&
        Objects.equals(this.webSite, companyContactInfo.webSite) &&
        Objects.equals(this.regNumber, companyContactInfo.regNumber) &&
        Objects.equals(this.taxNumber, companyContactInfo.taxNumber) &&
        Objects.equals(this.vatNumber, companyContactInfo.vatNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, logoUrl, address, otherAddress, postalCode, city, country, email, phone, otherPhone, fax, icqNumber, skype, webSite, regNumber, taxNumber, vatNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyContactInfo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    otherAddress: ").append(toIndentedString(otherAddress)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    otherPhone: ").append(toIndentedString(otherPhone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    icqNumber: ").append(toIndentedString(icqNumber)).append("\n");
    sb.append("    skype: ").append(toIndentedString(skype)).append("\n");
    sb.append("    webSite: ").append(toIndentedString(webSite)).append("\n");
    sb.append("    regNumber: ").append(toIndentedString(regNumber)).append("\n");
    sb.append("    taxNumber: ").append(toIndentedString(taxNumber)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

