/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.RaceParticipant;
import java.io.IOException;
import java.util.List;

/**
 * The Dirttrack participant information. 
 */
@ApiModel(description = "The Dirttrack participant information. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class DirttrackParticipant extends RaceParticipant {
  @SerializedName("speed")
  private Float speed = null;

  @SerializedName("stamina")
  private Float stamina = null;

  @SerializedName("wins")
  private Float wins = null;

  public DirttrackParticipant speed(Float speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Participant speed
   * @return speed
  **/
  @ApiModelProperty(value = "Participant speed")
  public Float getSpeed() {
    return speed;
  }

  public void setSpeed(Float speed) {
    this.speed = speed;
  }

  public DirttrackParticipant stamina(Float stamina) {
    this.stamina = stamina;
    return this;
  }

   /**
   * Participant stamina
   * @return stamina
  **/
  @ApiModelProperty(value = "Participant stamina")
  public Float getStamina() {
    return stamina;
  }

  public void setStamina(Float stamina) {
    this.stamina = stamina;
  }

  public DirttrackParticipant wins(Float wins) {
    this.wins = wins;
    return this;
  }

   /**
   * Participant victories
   * @return wins
  **/
  @ApiModelProperty(value = "Participant victories")
  public Float getWins() {
    return wins;
  }

  public void setWins(Float wins) {
    this.wins = wins;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DirttrackParticipant dirttrackParticipant = (DirttrackParticipant) o;
    return Objects.equals(this.speed, dirttrackParticipant.speed) &&
        Objects.equals(this.stamina, dirttrackParticipant.stamina) &&
        Objects.equals(this.wins, dirttrackParticipant.wins) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speed, stamina, wins, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DirttrackParticipant {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    stamina: ").append(toIndentedString(stamina)).append("\n");
    sb.append("    wins: ").append(toIndentedString(wins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

