/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.EvResult;
import com.panda.sport.rcs.virtual.third.client.model.LottofiveDrawResult;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Information about result of Lotto Five event blocks. 
 */
@ApiModel(description = "Information about result of Lotto Five event blocks. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class EvResultLottofive extends EvResult {
  @SerializedName("resultVideoURL")
  private String resultVideoURL = null;

  @SerializedName("drawDate")
  private OffsetDateTime drawDate = null;

  @SerializedName("result")
  private LottofiveDrawResult result = null;

  public EvResultLottofive resultVideoURL(String resultVideoURL) {
    this.resultVideoURL = resultVideoURL;
    return this;
  }

   /**
   * URL of the event result video
   * @return resultVideoURL
  **/
  @ApiModelProperty(value = "URL of the event result video")
  public String getResultVideoURL() {
    return resultVideoURL;
  }

  public void setResultVideoURL(String resultVideoURL) {
    this.resultVideoURL = resultVideoURL;
  }

  public EvResultLottofive drawDate(OffsetDateTime drawDate) {
    this.drawDate = drawDate;
    return this;
  }

   /**
   * Get drawDate
   * @return drawDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDrawDate() {
    return drawDate;
  }

  public void setDrawDate(OffsetDateTime drawDate) {
    this.drawDate = drawDate;
  }

  public EvResultLottofive result(LottofiveDrawResult result) {
    this.result = result;
    return this;
  }

   /**
   * Array of draw results.
   * @return result
  **/
  @ApiModelProperty(value = "Array of draw results.")
  public LottofiveDrawResult getResult() {
    return result;
  }

  public void setResult(LottofiveDrawResult result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvResultLottofive evResultLottofive = (EvResultLottofive) o;
    return Objects.equals(this.resultVideoURL, evResultLottofive.resultVideoURL) &&
        Objects.equals(this.drawDate, evResultLottofive.drawDate) &&
        Objects.equals(this.result, evResultLottofive.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultVideoURL, drawDate, result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvResultLottofive {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    resultVideoURL: ").append(toIndentedString(resultVideoURL)).append("\n");
    sb.append("    drawDate: ").append(toIndentedString(drawDate)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

