/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.Participant;
import java.io.IOException;

/**
 * The football participant information. 
 */
@ApiModel(description = "The football participant information. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class FootballParticipant extends Participant {
  @SerializedName("name")
  private String name = null;

  @SerializedName("shortDesc")
  private String shortDesc = null;

  @SerializedName("longDesc")
  private String longDesc = null;

  @SerializedName("fifaCode")
  private String fifaCode = null;

  @SerializedName("stars")
  private Double stars = null;

  public FootballParticipant name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Participant Name
   * @return name
  **/
  @ApiModelProperty(value = "Participant Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FootballParticipant shortDesc(String shortDesc) {
    this.shortDesc = shortDesc;
    return this;
  }

   /**
   * Participant short description
   * @return shortDesc
  **/
  @ApiModelProperty(value = "Participant short description")
  public String getShortDesc() {
    return shortDesc;
  }

  public void setShortDesc(String shortDesc) {
    this.shortDesc = shortDesc;
  }

  public FootballParticipant longDesc(String longDesc) {
    this.longDesc = longDesc;
    return this;
  }

   /**
   * Participant long description
   * @return longDesc
  **/
  @ApiModelProperty(value = "Participant long description")
  public String getLongDesc() {
    return longDesc;
  }

  public void setLongDesc(String longDesc) {
    this.longDesc = longDesc;
  }

  public FootballParticipant fifaCode(String fifaCode) {
    this.fifaCode = fifaCode;
    return this;
  }

   /**
   * Participant FIFA code
   * @return fifaCode
  **/
  @ApiModelProperty(value = "Participant FIFA code")
  public String getFifaCode() {
    return fifaCode;
  }

  public void setFifaCode(String fifaCode) {
    this.fifaCode = fifaCode;
  }

  public FootballParticipant stars(Double stars) {
    this.stars = stars;
    return this;
  }

   /**
   * Team quality value from 1 to 5. 
   * @return stars
  **/
  @ApiModelProperty(value = "Team quality value from 1 to 5. ")
  public Double getStars() {
    return stars;
  }

  public void setStars(Double stars) {
    this.stars = stars;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FootballParticipant footballParticipant = (FootballParticipant) o;
    return Objects.equals(this.name, footballParticipant.name) &&
        Objects.equals(this.shortDesc, footballParticipant.shortDesc) &&
        Objects.equals(this.longDesc, footballParticipant.longDesc) &&
        Objects.equals(this.fifaCode, footballParticipant.fifaCode) &&
        Objects.equals(this.stars, footballParticipant.stars) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, shortDesc, longDesc, fifaCode, stars, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FootballParticipant {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shortDesc: ").append(toIndentedString(shortDesc)).append("\n");
    sb.append("    longDesc: ").append(toIndentedString(longDesc)).append("\n");
    sb.append("    fifaCode: ").append(toIndentedString(fifaCode)).append("\n");
    sb.append("    stars: ").append(toIndentedString(stars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

