/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.Context;
import com.panda.sport.rcs.virtual.third.client.model.Display;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Viewer independent configuration per playlist Client side options to enable / disable capabilities of games. Management of all behavior options per game, not related to odds/tickets calculation, and generic for all games. 
 */
@ApiModel(description = "Viewer independent configuration per playlist Client side options to enable / disable capabilities of games. Management of all behavior options per game, not related to odds/tickets calculation, and generic for all games. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class GameContext extends Context {
  @SerializedName("displays")
  private List<Display> displays = null;

  public GameContext displays(List<Display> displays) {
    this.displays = displays;
    return this;
  }

  public GameContext addDisplaysItem(Display displaysItem) {
    if (this.displays == null) {
      this.displays = new ArrayList<Display>();
    }
    this.displays.add(displaysItem);
    return this;
  }

   /**
   * Enable games, grouped in &#39;displays&#39;. 
   * @return displays
  **/
  @ApiModelProperty(value = "Enable games, grouped in 'displays'. ")
  public List<Display> getDisplays() {
    return displays;
  }

  public void setDisplays(List<Display> displays) {
    this.displays = displays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameContext gameContext = (GameContext) o;
    return Objects.equals(this.displays, gameContext.displays) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displays, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameContext {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    displays: ").append(toIndentedString(displays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

