/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.RacesAssets;
import java.io.IOException;

/**
 * Assets configuration of horse playlist 
 */
@ApiModel(description = "Assets configuration of horse playlist ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class HorseAssets extends RacesAssets {
  @SerializedName("is3D")
  private Boolean is3D = null;

  @SerializedName("auroraGtpacksId")
  private String auroraGtpacksId = null;

  public HorseAssets is3D(Boolean is3D) {
    this.is3D = is3D;
    return this;
  }

   /**
   * If true, game is presented in 3D view.
   * @return is3D
  **/
  @ApiModelProperty(value = "If true, game is presented in 3D view.")
  public Boolean isIs3D() {
    return is3D;
  }

  public void setIs3D(Boolean is3D) {
    this.is3D = is3D;
  }

  public HorseAssets auroraGtpacksId(String auroraGtpacksId) {
    this.auroraGtpacksId = auroraGtpacksId;
    return this;
  }

   /**
   * Id to Aurora for loading library purpose. Posible values are;   - horses -&gt; horse for 6 participants   - horses12 -&gt; horse for 12 participants   - horses12la -&gt; horse for 12 participants 
   * @return auroraGtpacksId
  **/
  @ApiModelProperty(value = "Id to Aurora for loading library purpose. Posible values are;   - horses -> horse for 6 participants   - horses12 -> horse for 12 participants   - horses12la -> horse for 12 participants ")
  public String getAuroraGtpacksId() {
    return auroraGtpacksId;
  }

  public void setAuroraGtpacksId(String auroraGtpacksId) {
    this.auroraGtpacksId = auroraGtpacksId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HorseAssets horseAssets = (HorseAssets) o;
    return Objects.equals(this.is3D, horseAssets.is3D) &&
        Objects.equals(this.auroraGtpacksId, horseAssets.auroraGtpacksId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(is3D, auroraGtpacksId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HorseAssets {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    is3D: ").append(toIndentedString(is3D)).append("\n");
    sb.append("    auroraGtpacksId: ").append(toIndentedString(auroraGtpacksId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

