/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.ReportParams;
import com.panda.sport.rcs.virtual.third.client.model.ReportTarget;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Internal Invoice report parameters
 */
@ApiModel(description = "Internal Invoice report parameters")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class InvoiceReportParams extends ReportParams {
  @SerializedName("produces")
  private String produces = "application/pdf";

  @SerializedName("invoiceNumber")
  private String invoiceNumber = null;

  @SerializedName("invoiceDate")
  private OffsetDateTime invoiceDate = null;

  @SerializedName("outputCurrency")
  private String outputCurrency = null;

  @SerializedName("companyBaseId")
  private Integer companyBaseId = null;

  @SerializedName("companyTargetId")
  private Integer companyTargetId = null;

  public InvoiceReportParams produces(String produces) {
    this.produces = produces;
    return this;
  }

   /**
   * Produces. 
   * @return produces
  **/
  @ApiModelProperty(required = true, value = "Produces. ")
  public String getProduces() {
    return produces;
  }

  public void setProduces(String produces) {
    this.produces = produces;
  }

  public InvoiceReportParams invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Invoice number
   * @return invoiceNumber
  **/
  @ApiModelProperty(required = true, value = "Invoice number")
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public InvoiceReportParams invoiceDate(OffsetDateTime invoiceDate) {
    this.invoiceDate = invoiceDate;
    return this;
  }

   /**
   * Invoice date
   * @return invoiceDate
  **/
  @ApiModelProperty(required = true, value = "Invoice date")
  public OffsetDateTime getInvoiceDate() {
    return invoiceDate;
  }

  public void setInvoiceDate(OffsetDateTime invoiceDate) {
    this.invoiceDate = invoiceDate;
  }

  public InvoiceReportParams outputCurrency(String outputCurrency) {
    this.outputCurrency = outputCurrency;
    return this;
  }

   /**
   * Output currency
   * @return outputCurrency
  **/
  @ApiModelProperty(required = true, value = "Output currency")
  public String getOutputCurrency() {
    return outputCurrency;
  }

  public void setOutputCurrency(String outputCurrency) {
    this.outputCurrency = outputCurrency;
  }

  public InvoiceReportParams companyBaseId(Integer companyBaseId) {
    this.companyBaseId = companyBaseId;
    return this;
  }

   /**
   * Company Base Id. The entity id of the company which remit the invoice.
   * @return companyBaseId
  **/
  @ApiModelProperty(required = true, value = "Company Base Id. The entity id of the company which remit the invoice.")
  public Integer getCompanyBaseId() {
    return companyBaseId;
  }

  public void setCompanyBaseId(Integer companyBaseId) {
    this.companyBaseId = companyBaseId;
  }

  public InvoiceReportParams companyTargetId(Integer companyTargetId) {
    this.companyTargetId = companyTargetId;
    return this;
  }

   /**
   * Company Target Id. The entity id of the company which pay the invoice.
   * @return companyTargetId
  **/
  @ApiModelProperty(required = true, value = "Company Target Id. The entity id of the company which pay the invoice.")
  public Integer getCompanyTargetId() {
    return companyTargetId;
  }

  public void setCompanyTargetId(Integer companyTargetId) {
    this.companyTargetId = companyTargetId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceReportParams invoiceReportParams = (InvoiceReportParams) o;
    return Objects.equals(this.produces, invoiceReportParams.produces) &&
        Objects.equals(this.invoiceNumber, invoiceReportParams.invoiceNumber) &&
        Objects.equals(this.invoiceDate, invoiceReportParams.invoiceDate) &&
        Objects.equals(this.outputCurrency, invoiceReportParams.outputCurrency) &&
        Objects.equals(this.companyBaseId, invoiceReportParams.companyBaseId) &&
        Objects.equals(this.companyTargetId, invoiceReportParams.companyTargetId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(produces, invoiceNumber, invoiceDate, outputCurrency, companyBaseId, companyTargetId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceReportParams {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    produces: ").append(toIndentedString(produces)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    invoiceDate: ").append(toIndentedString(invoiceDate)).append("\n");
    sb.append("    outputCurrency: ").append(toIndentedString(outputCurrency)).append("\n");
    sb.append("    companyBaseId: ").append(toIndentedString(companyBaseId)).append("\n");
    sb.append("    companyTargetId: ").append(toIndentedString(companyTargetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

