/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Level Tax 
 */
@ApiModel(description = "Level Tax ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class LevelTax {
  @SerializedName("levelId")
  private String levelId = null;

  @SerializedName("threshold")
  private Double threshold = null;

  @SerializedName("taxPercent")
  private Double taxPercent = null;

  public LevelTax levelId(String levelId) {
    this.levelId = levelId;
    return this;
  }

   /**
   * Unique number Id for tax level 
   * @return levelId
  **/
  @ApiModelProperty(required = true, value = "Unique number Id for tax level ")
  public String getLevelId() {
    return levelId;
  }

  public void setLevelId(String levelId) {
    this.levelId = levelId;
  }

  public LevelTax threshold(Double threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Payout amount from which start to apply taxes 
   * minimum: 0
   * @return threshold
  **/
  @ApiModelProperty(value = "Payout amount from which start to apply taxes ")
  public Double getThreshold() {
    return threshold;
  }

  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }

  public LevelTax taxPercent(Double taxPercent) {
    this.taxPercent = taxPercent;
    return this;
  }

   /**
   * Tax Percentage of level    
   * minimum: 0
   * @return taxPercent
  **/
  @ApiModelProperty(value = "Tax Percentage of level    ")
  public Double getTaxPercent() {
    return taxPercent;
  }

  public void setTaxPercent(Double taxPercent) {
    this.taxPercent = taxPercent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelTax levelTax = (LevelTax) o;
    return Objects.equals(this.levelId, levelTax.levelId) &&
        Objects.equals(this.threshold, levelTax.threshold) &&
        Objects.equals(this.taxPercent, levelTax.taxPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(levelId, threshold, taxPercent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelTax {\n");
    
    sb.append("    levelId: ").append(toIndentedString(levelId)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    taxPercent: ").append(toIndentedString(taxPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

