/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.TickerGameSetting;
import com.panda.sport.rcs.virtual.third.client.model.ViewerProfileGameSettings;
import java.io.IOException;
import java.util.List;

/**
 * Ll Viewer Profile Game Settings 
 */
@ApiModel(description = "Ll Viewer Profile Game Settings ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class LlViewerProfileGameSettings extends ViewerProfileGameSettings {
  /**
   * Panels 
   */
  @JsonAdapter(PanelsEnum.Adapter.class)
  public enum PanelsEnum {
    MARKETANDSTATS("MARKETANDSTATS"),
    
    MARKETS("MARKETS"),
    
    STATS("STATS");

    private String value;

    PanelsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PanelsEnum fromValue(String text) {
      for (PanelsEnum b : PanelsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PanelsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PanelsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PanelsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PanelsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("panels")
  private PanelsEnum panels = null;

  /**
   * Identifier 
   */
  @JsonAdapter(IdentifierEnum.Adapter.class)
  public enum IdentifierEnum {
    INTERNAL("INTERNAL"),
    
    LEGACY("LEGACY");

    private String value;

    IdentifierEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IdentifierEnum fromValue(String text) {
      for (IdentifierEnum b : IdentifierEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<IdentifierEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IdentifierEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IdentifierEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return IdentifierEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("identifier")
  private IdentifierEnum identifier = null;

  public LlViewerProfileGameSettings panels(PanelsEnum panels) {
    this.panels = panels;
    return this;
  }

   /**
   * Panels 
   * @return panels
  **/
  @ApiModelProperty(value = "Panels ")
  public PanelsEnum getPanels() {
    return panels;
  }

  public void setPanels(PanelsEnum panels) {
    this.panels = panels;
  }

  public LlViewerProfileGameSettings identifier(IdentifierEnum identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Identifier 
   * @return identifier
  **/
  @ApiModelProperty(value = "Identifier ")
  public IdentifierEnum getIdentifier() {
    return identifier;
  }

  public void setIdentifier(IdentifierEnum identifier) {
    this.identifier = identifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LlViewerProfileGameSettings llViewerProfileGameSettings = (LlViewerProfileGameSettings) o;
    return Objects.equals(this.panels, llViewerProfileGameSettings.panels) &&
        Objects.equals(this.identifier, llViewerProfileGameSettings.identifier) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(panels, identifier, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LlViewerProfileGameSettings {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    panels: ").append(toIndentedString(panels)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

