/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.LottofiveStatsDrawDay;
import com.panda.sport.rcs.virtual.third.client.model.LottofiveStatsTicketPrize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Information about the biggest prizes of the stats 
 */
@ApiModel(description = "Information about the biggest prizes of the stats ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class LottofiveStatEver {
  @SerializedName("historic")
  private LottofiveStatsTicketPrize historic = null;

  @SerializedName("draws")
  private List<LottofiveStatsDrawDay> draws = null;

  public LottofiveStatEver historic(LottofiveStatsTicketPrize historic) {
    this.historic = historic;
    return this;
  }

   /**
   * Biggest prize of the stats 
   * @return historic
  **/
  @ApiModelProperty(value = "Biggest prize of the stats ")
  public LottofiveStatsTicketPrize getHistoric() {
    return historic;
  }

  public void setHistoric(LottofiveStatsTicketPrize historic) {
    this.historic = historic;
  }

  public LottofiveStatEver draws(List<LottofiveStatsDrawDay> draws) {
    this.draws = draws;
    return this;
  }

  public LottofiveStatEver addDrawsItem(LottofiveStatsDrawDay drawsItem) {
    if (this.draws == null) {
      this.draws = new ArrayList<LottofiveStatsDrawDay>();
    }
    this.draws.add(drawsItem);
    return this;
  }

   /**
   * Information about the stats of each draw in one day 
   * @return draws
  **/
  @ApiModelProperty(value = "Information about the stats of each draw in one day ")
  public List<LottofiveStatsDrawDay> getDraws() {
    return draws;
  }

  public void setDraws(List<LottofiveStatsDrawDay> draws) {
    this.draws = draws;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottofiveStatEver lottofiveStatEver = (LottofiveStatEver) o;
    return Objects.equals(this.historic, lottofiveStatEver.historic) &&
        Objects.equals(this.draws, lottofiveStatEver.draws);
  }

  @Override
  public int hashCode() {
    return Objects.hash(historic, draws);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottofiveStatEver {\n");
    
    sb.append("    historic: ").append(toIndentedString(historic)).append("\n");
    sb.append("    draws: ").append(toIndentedString(draws)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

