/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.Filter;
import com.panda.sport.rcs.virtual.third.client.model.LottofiveColourConfiguration;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Configuration of Lottofive Playlist 
 */
@ApiModel(description = "Configuration of Lottofive Playlist ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class LottofiveFilter extends Filter {
  @SerializedName("colourConfigurations")
  private List<LottofiveColourConfiguration> colourConfigurations = null;

  public LottofiveFilter colourConfigurations(List<LottofiveColourConfiguration> colourConfigurations) {
    this.colourConfigurations = colourConfigurations;
    return this;
  }

  public LottofiveFilter addColourConfigurationsItem(LottofiveColourConfiguration colourConfigurationsItem) {
    if (this.colourConfigurations == null) {
      this.colourConfigurations = new ArrayList<LottofiveColourConfiguration>();
    }
    this.colourConfigurations.add(colourConfigurationsItem);
    return this;
  }

   /**
   * List of colour balls definitions
   * @return colourConfigurations
  **/
  @ApiModelProperty(value = "List of colour balls definitions")
  public List<LottofiveColourConfiguration> getColourConfigurations() {
    return colourConfigurations;
  }

  public void setColourConfigurations(List<LottofiveColourConfiguration> colourConfigurations) {
    this.colourConfigurations = colourConfigurations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottofiveFilter lottofiveFilter = (LottofiveFilter) o;
    return Objects.equals(this.colourConfigurations, lottofiveFilter.colourConfigurations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(colourConfigurations, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottofiveFilter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    colourConfigurations: ").append(toIndentedString(colourConfigurations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

