/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.LottofiveStatsDrawDay;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Information about the stats of the day. 
 */
@ApiModel(description = "Information about the stats of the day. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class LottofiveStatsDay {
  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("stats")
  private List<LottofiveStatsDrawDay> stats = null;

  public LottofiveStatsDay date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Date of the stat 
   * @return date
  **/
  @ApiModelProperty(value = "Date of the stat ")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public LottofiveStatsDay stats(List<LottofiveStatsDrawDay> stats) {
    this.stats = stats;
    return this;
  }

  public LottofiveStatsDay addStatsItem(LottofiveStatsDrawDay statsItem) {
    if (this.stats == null) {
      this.stats = new ArrayList<LottofiveStatsDrawDay>();
    }
    this.stats.add(statsItem);
    return this;
  }

   /**
   * Information about the stats of each draw in one day 
   * @return stats
  **/
  @ApiModelProperty(value = "Information about the stats of each draw in one day ")
  public List<LottofiveStatsDrawDay> getStats() {
    return stats;
  }

  public void setStats(List<LottofiveStatsDrawDay> stats) {
    this.stats = stats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottofiveStatsDay lottofiveStatsDay = (LottofiveStatsDay) o;
    return Objects.equals(this.date, lottofiveStatsDay.date) &&
        Objects.equals(this.stats, lottofiveStatsDay.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, stats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottofiveStatsDay {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

