/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Limits and odd settings per market/bet 
 */
@ApiModel(description = "Limits and odd settings per market/bet ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class OddSettings {
  @SerializedName("key")
  private String key = null;

  @SerializedName("overround")
  private Double overround = null;

  public OddSettings key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public OddSettings overround(Double overround) {
    this.overround = overround;
    return this;
  }

   /**
   * Overround for odd. Overround can be expressed as 1/payout.  Final odd can be calculated from probaility and overround, maxOdd. 
   * @return overround
  **/
  @ApiModelProperty(value = "Overround for odd. Overround can be expressed as 1/payout.  Final odd can be calculated from probaility and overround, maxOdd. ")
  public Double getOverround() {
    return overround;
  }

  public void setOverround(Double overround) {
    this.overround = overround;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OddSettings oddSettings = (OddSettings) o;
    return Objects.equals(this.key, oddSettings.key) &&
        Objects.equals(this.overround, oddSettings.overround);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, overround);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OddSettings {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    overround: ").append(toIndentedString(overround)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

