/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.BetslipProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.CashierProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.Context;
import com.panda.sport.rcs.virtual.third.client.model.MobileProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.PrintProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.ShopadminProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.ViewerProfileSettings;
import com.panda.sport.rcs.virtual.third.client.model.WebProfileSettings;
import java.io.IOException;

/**
 * ProfilesContext
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class ProfilesContext extends Context {
  @SerializedName("cashier")
  private CashierProfileSettings cashier = null;

  @SerializedName("viewer")
  private ViewerProfileSettings viewer = null;

  @SerializedName("print")
  private PrintProfileSettings print = null;

  @SerializedName("shopadmin")
  private ShopadminProfileSettings shopadmin = null;

  @SerializedName("mobile")
  private MobileProfileSettings mobile = null;

  @SerializedName("web")
  private WebProfileSettings web = null;

  @SerializedName("betslip")
  private BetslipProfileSettings betslip = null;

  public ProfilesContext cashier(CashierProfileSettings cashier) {
    this.cashier = cashier;
    return this;
  }

   /**
   * Get cashier
   * @return cashier
  **/
  @ApiModelProperty(value = "")
  public CashierProfileSettings getCashier() {
    return cashier;
  }

  public void setCashier(CashierProfileSettings cashier) {
    this.cashier = cashier;
  }

  public ProfilesContext viewer(ViewerProfileSettings viewer) {
    this.viewer = viewer;
    return this;
  }

   /**
   * Get viewer
   * @return viewer
  **/
  @ApiModelProperty(value = "")
  public ViewerProfileSettings getViewer() {
    return viewer;
  }

  public void setViewer(ViewerProfileSettings viewer) {
    this.viewer = viewer;
  }

  public ProfilesContext print(PrintProfileSettings print) {
    this.print = print;
    return this;
  }

   /**
   * Get print
   * @return print
  **/
  @ApiModelProperty(value = "")
  public PrintProfileSettings getPrint() {
    return print;
  }

  public void setPrint(PrintProfileSettings print) {
    this.print = print;
  }

  public ProfilesContext shopadmin(ShopadminProfileSettings shopadmin) {
    this.shopadmin = shopadmin;
    return this;
  }

   /**
   * Get shopadmin
   * @return shopadmin
  **/
  @ApiModelProperty(value = "")
  public ShopadminProfileSettings getShopadmin() {
    return shopadmin;
  }

  public void setShopadmin(ShopadminProfileSettings shopadmin) {
    this.shopadmin = shopadmin;
  }

  public ProfilesContext mobile(MobileProfileSettings mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  @ApiModelProperty(value = "")
  public MobileProfileSettings getMobile() {
    return mobile;
  }

  public void setMobile(MobileProfileSettings mobile) {
    this.mobile = mobile;
  }

  public ProfilesContext web(WebProfileSettings web) {
    this.web = web;
    return this;
  }

   /**
   * Get web
   * @return web
  **/
  @ApiModelProperty(value = "")
  public WebProfileSettings getWeb() {
    return web;
  }

  public void setWeb(WebProfileSettings web) {
    this.web = web;
  }

  public ProfilesContext betslip(BetslipProfileSettings betslip) {
    this.betslip = betslip;
    return this;
  }

   /**
   * Get betslip
   * @return betslip
  **/
  @ApiModelProperty(value = "")
  public BetslipProfileSettings getBetslip() {
    return betslip;
  }

  public void setBetslip(BetslipProfileSettings betslip) {
    this.betslip = betslip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfilesContext profilesContext = (ProfilesContext) o;
    return Objects.equals(this.cashier, profilesContext.cashier) &&
        Objects.equals(this.viewer, profilesContext.viewer) &&
        Objects.equals(this.print, profilesContext.print) &&
        Objects.equals(this.shopadmin, profilesContext.shopadmin) &&
        Objects.equals(this.mobile, profilesContext.mobile) &&
        Objects.equals(this.web, profilesContext.web) &&
        Objects.equals(this.betslip, profilesContext.betslip) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashier, viewer, print, shopadmin, mobile, web, betslip, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfilesContext {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    cashier: ").append(toIndentedString(cashier)).append("\n");
    sb.append("    viewer: ").append(toIndentedString(viewer)).append("\n");
    sb.append("    print: ").append(toIndentedString(print)).append("\n");
    sb.append("    shopadmin: ").append(toIndentedString(shopadmin)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    web: ").append(toIndentedString(web)).append("\n");
    sb.append("    betslip: ").append(toIndentedString(betslip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

