/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.EventResultData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TODO 
 */
@ApiModel(description = "TODO ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class RaceEventResultData extends EventResultData {
  @SerializedName("hlsURL")
  private String hlsURL = null;

  @SerializedName("mediaId")
  private String mediaId = null;

  @SerializedName("mediaSignature")
  private String mediaSignature = null;

  @SerializedName("mediaExpireTime")
  private Long mediaExpireTime = null;

  @SerializedName("happenings")
  private String happenings = null;

  @SerializedName("finalOrder")
  private List<String> finalOrder = null;

  public RaceEventResultData hlsURL(String hlsURL) {
    this.hlsURL = hlsURL;
    return this;
  }

   /**
   * DEPRECATED. HLS Video URL to show de event result 
   * @return hlsURL
  **/
  @ApiModelProperty(value = "DEPRECATED. HLS Video URL to show de event result ")
  public String getHlsURL() {
    return hlsURL;
  }

  public void setHlsURL(String hlsURL) {
    this.hlsURL = hlsURL;
  }

  public RaceEventResultData mediaId(String mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Multimedia resource identifier associated with the OCV or HLS to be used in the ingame. This attribute will be used to generate the OCV or HLS video url. For OCV, this identifier is the same for both video and voice-over 
   * @return mediaId
  **/
  @ApiModelProperty(value = "Multimedia resource identifier associated with the OCV or HLS to be used in the ingame. This attribute will be used to generate the OCV or HLS video url. For OCV, this identifier is the same for both video and voice-over ")
  public String getMediaId() {
    return mediaId;
  }

  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }

  public RaceEventResultData mediaSignature(String mediaSignature) {
    this.mediaSignature = mediaSignature;
    return this;
  }

   /**
   * Server generated time signature. It is used for the securization of multimedia resources. Generation method -&gt; digestfunction (timestamp + InternalApiKey).  This attribute will be used to generate the OCV or HLS video url. 
   * @return mediaSignature
  **/
  @ApiModelProperty(value = "Server generated time signature. It is used for the securization of multimedia resources. Generation method -> digestfunction (timestamp + InternalApiKey).  This attribute will be used to generate the OCV or HLS video url. ")
  public String getMediaSignature() {
    return mediaSignature;
  }

  public void setMediaSignature(String mediaSignature) {
    this.mediaSignature = mediaSignature;
  }

  public RaceEventResultData mediaExpireTime(Long mediaExpireTime) {
    this.mediaExpireTime = mediaExpireTime;
    return this;
  }

   /**
   * Expiration time for the signature (in UTC). If the current timestamp is older than the one given, the multimedia resources will not be accessible.  This attribute will be used to generate the OCV or HLS video url. 
   * @return mediaExpireTime
  **/
  @ApiModelProperty(value = "Expiration time for the signature (in UTC). If the current timestamp is older than the one given, the multimedia resources will not be accessible.  This attribute will be used to generate the OCV or HLS video url. ")
  public Long getMediaExpireTime() {
    return mediaExpireTime;
  }

  public void setMediaExpireTime(Long mediaExpireTime) {
    this.mediaExpireTime = mediaExpireTime;
  }

  public RaceEventResultData happenings(String happenings) {
    this.happenings = happenings;
    return this;
  }

   /**
   * Text string encoded with the events that happen in the reproduction of the event, such as when a goal happens. 
   * @return happenings
  **/
  @ApiModelProperty(value = "Text string encoded with the events that happen in the reproduction of the event, such as when a goal happens. ")
  public String getHappenings() {
    return happenings;
  }

  public void setHappenings(String happenings) {
    this.happenings = happenings;
  }

  public RaceEventResultData finalOrder(List<String> finalOrder) {
    this.finalOrder = finalOrder;
    return this;
  }

  public RaceEventResultData addFinalOrderItem(String finalOrderItem) {
    if (this.finalOrder == null) {
      this.finalOrder = new ArrayList<String>();
    }
    this.finalOrder.add(finalOrderItem);
    return this;
  }

   /**
   * It represents the finish order of ALL participants (not just the podium participants). For example, if a race has 8 participants, the finalOrder will have a size of 8. 
   * @return finalOrder
  **/
  @ApiModelProperty(value = "It represents the finish order of ALL participants (not just the podium participants). For example, if a race has 8 participants, the finalOrder will have a size of 8. ")
  public List<String> getFinalOrder() {
    return finalOrder;
  }

  public void setFinalOrder(List<String> finalOrder) {
    this.finalOrder = finalOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceEventResultData raceEventResultData = (RaceEventResultData) o;
    return Objects.equals(this.hlsURL, raceEventResultData.hlsURL) &&
        Objects.equals(this.mediaId, raceEventResultData.mediaId) &&
        Objects.equals(this.mediaSignature, raceEventResultData.mediaSignature) &&
        Objects.equals(this.mediaExpireTime, raceEventResultData.mediaExpireTime) &&
        Objects.equals(this.happenings, raceEventResultData.happenings) &&
        Objects.equals(this.finalOrder, raceEventResultData.finalOrder) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hlsURL, mediaId, mediaSignature, mediaExpireTime, happenings, finalOrder, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceEventResultData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    hlsURL: ").append(toIndentedString(hlsURL)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    mediaSignature: ").append(toIndentedString(mediaSignature)).append("\n");
    sb.append("    mediaExpireTime: ").append(toIndentedString(mediaExpireTime)).append("\n");
    sb.append("    happenings: ").append(toIndentedString(happenings)).append("\n");
    sb.append("    finalOrder: ").append(toIndentedString(finalOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

