/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.EntityBodyMessage;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * A message indicating that the entity must be restarted 
 */
@ApiModel(description = "A message indicating that the entity must be restarted ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class ResetMessage extends EntityBodyMessage {
  @SerializedName("entityId")
  private Integer entityId = null;

  @SerializedName("executionDate")
  private BigDecimal executionDate = null;

  public ResetMessage entityId(Integer entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The entity that recieves the message
   * @return entityId
  **/
  @ApiModelProperty(value = "The entity that recieves the message")
  public Integer getEntityId() {
    return entityId;
  }

  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }

  public ResetMessage executionDate(BigDecimal executionDate) {
    this.executionDate = executionDate;
    return this;
  }

   /**
   * The date when we want to execute the restart.
   * @return executionDate
  **/
  @ApiModelProperty(value = "The date when we want to execute the restart.")
  public BigDecimal getExecutionDate() {
    return executionDate;
  }

  public void setExecutionDate(BigDecimal executionDate) {
    this.executionDate = executionDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetMessage resetMessage = (ResetMessage) o;
    return Objects.equals(this.entityId, resetMessage.entityId) &&
        Objects.equals(this.executionDate, resetMessage.executionDate) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, executionDate, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetMessage {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    executionDate: ").append(toIndentedString(executionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

