/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Object to define the relationship between profiles and rights linked to an API context 
 */
@ApiModel(description = "Object to define the relationship between profiles and rights linked to an API context ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class RightProfile {
  @SerializedName("entityId")
  private Integer entityId = null;

  @SerializedName("fatherId")
  private Integer fatherId = null;

  @SerializedName("status")
  private Boolean status = null;

  public RightProfile entityId(Integer entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The entity identifier of the right
   * @return entityId
  **/
  @ApiModelProperty(value = "The entity identifier of the right")
  public Integer getEntityId() {
    return entityId;
  }

  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }

  public RightProfile fatherId(Integer fatherId) {
    this.fatherId = fatherId;
    return this;
  }

   /**
   * The entity father identifier of the right
   * @return fatherId
  **/
  @ApiModelProperty(value = "The entity father identifier of the right")
  public Integer getFatherId() {
    return fatherId;
  }

  public void setFatherId(Integer fatherId) {
    this.fatherId = fatherId;
  }

  public RightProfile status(Boolean status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the relationship between an entity and a profile entity (0 inactive, 1 active).
   * @return status
  **/
  @ApiModelProperty(value = "The status of the relationship between an entity and a profile entity (0 inactive, 1 active).")
  public Boolean isStatus() {
    return status;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RightProfile rightProfile = (RightProfile) o;
    return Objects.equals(this.entityId, rightProfile.entityId) &&
        Objects.equals(this.fatherId, rightProfile.fatherId) &&
        Objects.equals(this.status, rightProfile.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, fatherId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RightProfile {\n");
    
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    fatherId: ").append(toIndentedString(fatherId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

