/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Risk Currency Setting. 
 */
@ApiModel(description = "Risk Currency Setting. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class RiskMgmtTypeSettings {
  @SerializedName("currency")
  private String currency = null;

  @SerializedName("maxLiability")
  private Double maxLiability = null;

  public RiskMgmtTypeSettings currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency ISO code. 
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "Currency ISO code. ")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public RiskMgmtTypeSettings maxLiability(Double maxLiability) {
    this.maxLiability = maxLiability;
    return this;
  }

   /**
   * Max individual liability allowed for one specific slot. 
   * minimum: 0
   * @return maxLiability
  **/
  @ApiModelProperty(value = "Max individual liability allowed for one specific slot. ")
  public Double getMaxLiability() {
    return maxLiability;
  }

  public void setMaxLiability(Double maxLiability) {
    this.maxLiability = maxLiability;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskMgmtTypeSettings riskMgmtTypeSettings = (RiskMgmtTypeSettings) o;
    return Objects.equals(this.currency, riskMgmtTypeSettings.currency) &&
        Objects.equals(this.maxLiability, riskMgmtTypeSettings.maxLiability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, maxLiability);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskMgmtTypeSettings {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    maxLiability: ").append(toIndentedString(maxLiability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

