/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Paytable details for Spin2Wheels game. 
 */
@ApiModel(description = "Paytable details for Spin2Wheels game. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class S2WPayTable {
  @SerializedName("odd")
  private Map<String, Double> odd = null;

  public S2WPayTable odd(Map<String, Double> odd) {
    this.odd = odd;
    return this;
  }

  public S2WPayTable putOddItem(String key, Double oddItem) {
    if (this.odd == null) {
      this.odd = new HashMap<String, Double>();
    }
    this.odd.put(key, oddItem);
    return this;
  }

   /**
   * Hash map indexed by bet id. Multiplier bets are indexed by using &amp;, while DoubleChance betsare indexed by using |. 
   * @return odd
  **/
  @ApiModelProperty(value = "Hash map indexed by bet id. Multiplier bets are indexed by using &, while DoubleChance betsare indexed by using |. ")
  public Map<String, Double> getOdd() {
    return odd;
  }

  public void setOdd(Map<String, Double> odd) {
    this.odd = odd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S2WPayTable s2WPayTable = (S2WPayTable) o;
    return Objects.equals(this.odd, s2WPayTable.odd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(odd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S2WPayTable {\n");
    
    sb.append("    odd: ").append(toIndentedString(odd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

