/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.ServerTicket;
import com.panda.sport.rcs.virtual.third.client.model.WalletRequest;
import java.io.IOException;

/**
 * SellRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class SellRequest extends WalletRequest {
  @SerializedName("ticket")
  private ServerTicket ticket = null;

  @SerializedName("extPromotionalWalletId")
  private String extPromotionalWalletId = null;

  public SellRequest ticket(ServerTicket ticket) {
    this.ticket = ticket;
    return this;
  }

   /**
   * Get ticket
   * @return ticket
  **/
  @ApiModelProperty(value = "")
  public ServerTicket getTicket() {
    return ticket;
  }

  public void setTicket(ServerTicket ticket) {
    this.ticket = ticket;
  }

  public SellRequest extPromotionalWalletId(String extPromotionalWalletId) {
    this.extPromotionalWalletId = extPromotionalWalletId;
    return this;
  }

   /**
   * 3rd party unique id for wallet to be used for promotional.
   * @return extPromotionalWalletId
  **/
  @ApiModelProperty(value = "3rd party unique id for wallet to be used for promotional.")
  public String getExtPromotionalWalletId() {
    return extPromotionalWalletId;
  }

  public void setExtPromotionalWalletId(String extPromotionalWalletId) {
    this.extPromotionalWalletId = extPromotionalWalletId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellRequest sellRequest = (SellRequest) o;
    return Objects.equals(this.ticket, sellRequest.ticket) &&
        Objects.equals(this.extPromotionalWalletId, sellRequest.extPromotionalWalletId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticket, extPromotionalWalletId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    ticket: ").append(toIndentedString(ticket)).append("\n");
    sb.append("    extPromotionalWalletId: ").append(toIndentedString(extPromotionalWalletId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

