/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SessionLog
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class SessionLog {
  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("lastSeen")
  private Long lastSeen = null;

  @SerializedName("loginTime")
  private Long loginTime = null;

  @SerializedName("credentialId")
  private Integer credentialId = null;

  @SerializedName("calculationId")
  private Integer calculationId = null;

  public SessionLog userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public SessionLog lastSeen(Long lastSeen) {
    this.lastSeen = lastSeen;
    return this;
  }

   /**
   * Last action done by the user.
   * @return lastSeen
  **/
  @ApiModelProperty(value = "Last action done by the user.")
  public Long getLastSeen() {
    return lastSeen;
  }

  public void setLastSeen(Long lastSeen) {
    this.lastSeen = lastSeen;
  }

  public SessionLog loginTime(Long loginTime) {
    this.loginTime = loginTime;
    return this;
  }

   /**
   * Last access by the user.
   * @return loginTime
  **/
  @ApiModelProperty(value = "Last access by the user.")
  public Long getLoginTime() {
    return loginTime;
  }

  public void setLoginTime(Long loginTime) {
    this.loginTime = loginTime;
  }

  public SessionLog credentialId(Integer credentialId) {
    this.credentialId = credentialId;
    return this;
  }

   /**
   * Depends on credentials used.
   * @return credentialId
  **/
  @ApiModelProperty(value = "Depends on credentials used.")
  public Integer getCredentialId() {
    return credentialId;
  }

  public void setCredentialId(Integer credentialId) {
    this.credentialId = credentialId;
  }

  public SessionLog calculationId(Integer calculationId) {
    this.calculationId = calculationId;
    return this;
  }

   /**
   * Get calculationId
   * @return calculationId
  **/
  @ApiModelProperty(value = "")
  public Integer getCalculationId() {
    return calculationId;
  }

  public void setCalculationId(Integer calculationId) {
    this.calculationId = calculationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionLog sessionLog = (SessionLog) o;
    return Objects.equals(this.userId, sessionLog.userId) &&
        Objects.equals(this.lastSeen, sessionLog.lastSeen) &&
        Objects.equals(this.loginTime, sessionLog.loginTime) &&
        Objects.equals(this.credentialId, sessionLog.credentialId) &&
        Objects.equals(this.calculationId, sessionLog.calculationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, lastSeen, loginTime, credentialId, calculationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionLog {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    loginTime: ").append(toIndentedString(loginTime)).append("\n");
    sb.append("    credentialId: ").append(toIndentedString(credentialId)).append("\n");
    sb.append("    calculationId: ").append(toIndentedString(calculationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

