/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.WinningData;
import com.panda.sport.rcs.virtual.third.client.model.WonData;
import java.io.IOException;

/**
 * Information about system bet. 
 */
@ApiModel(description = "Information about system bet. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class SystemBet {
  @SerializedName("grouping")
  private Integer grouping = null;

  @SerializedName("systemCount")
  private Integer systemCount = null;

  @SerializedName("stake")
  private Double stake = null;

  @SerializedName("cancelledStake")
  private Double cancelledStake = null;

  @SerializedName("winningData")
  private WinningData winningData = null;

  @SerializedName("wonData")
  private WonData wonData = null;

  public SystemBet grouping(Integer grouping) {
    this.grouping = grouping;
    return this;
  }

   /**
   * Grouping 
   * @return grouping
  **/
  @ApiModelProperty(required = true, value = "Grouping ")
  public Integer getGrouping() {
    return grouping;
  }

  public void setGrouping(Integer grouping) {
    this.grouping = grouping;
  }

  public SystemBet systemCount(Integer systemCount) {
    this.systemCount = systemCount;
    return this;
  }

   /**
   * Define the system betting count. 
   * @return systemCount
  **/
  @ApiModelProperty(value = "Define the system betting count. ")
  public Integer getSystemCount() {
    return systemCount;
  }

  public void setSystemCount(Integer systemCount) {
    this.systemCount = systemCount;
  }

  public SystemBet stake(Double stake) {
    this.stake = stake;
    return this;
  }

   /**
   * The stake value. 
   * @return stake
  **/
  @ApiModelProperty(required = true, value = "The stake value. ")
  public Double getStake() {
    return stake;
  }

  public void setStake(Double stake) {
    this.stake = stake;
  }

  public SystemBet cancelledStake(Double cancelledStake) {
    this.cancelledStake = cancelledStake;
    return this;
  }

   /**
   * The stake value for cancelled ticket. 
   * @return cancelledStake
  **/
  @ApiModelProperty(value = "The stake value for cancelled ticket. ")
  public Double getCancelledStake() {
    return cancelledStake;
  }

  public void setCancelledStake(Double cancelledStake) {
    this.cancelledStake = cancelledStake;
  }

  public SystemBet winningData(WinningData winningData) {
    this.winningData = winningData;
    return this;
  }

   /**
   * Get winningData
   * @return winningData
  **/
  @ApiModelProperty(value = "")
  public WinningData getWinningData() {
    return winningData;
  }

  public void setWinningData(WinningData winningData) {
    this.winningData = winningData;
  }

  public SystemBet wonData(WonData wonData) {
    this.wonData = wonData;
    return this;
  }

   /**
   * Get wonData
   * @return wonData
  **/
  @ApiModelProperty(value = "")
  public WonData getWonData() {
    return wonData;
  }

  public void setWonData(WonData wonData) {
    this.wonData = wonData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemBet systemBet = (SystemBet) o;
    return Objects.equals(this.grouping, systemBet.grouping) &&
        Objects.equals(this.systemCount, systemBet.systemCount) &&
        Objects.equals(this.stake, systemBet.stake) &&
        Objects.equals(this.cancelledStake, systemBet.cancelledStake) &&
        Objects.equals(this.winningData, systemBet.winningData) &&
        Objects.equals(this.wonData, systemBet.wonData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grouping, systemCount, stake, cancelledStake, winningData, wonData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemBet {\n");
    
    sb.append("    grouping: ").append(toIndentedString(grouping)).append("\n");
    sb.append("    systemCount: ").append(toIndentedString(systemCount)).append("\n");
    sb.append("    stake: ").append(toIndentedString(stake)).append("\n");
    sb.append("    cancelledStake: ").append(toIndentedString(cancelledStake)).append("\n");
    sb.append("    winningData: ").append(toIndentedString(winningData)).append("\n");
    sb.append("    wonData: ").append(toIndentedString(wonData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

