/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.EntityInfo;
import com.panda.sport.rcs.virtual.third.client.model.EntityStatus;
import com.panda.sport.rcs.virtual.third.client.model.EntityType;
import com.panda.sport.rcs.virtual.third.client.model.TreeItemParent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Information about one tree item. 
 */
@ApiModel(description = "Information about one tree item. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class TreeItem extends EntityInfo {
  @SerializedName("parents")
  private List<TreeItemParent> parents = null;

  public TreeItem parents(List<TreeItemParent> parents) {
    this.parents = parents;
    return this;
  }

  public TreeItem addParentsItem(TreeItemParent parentsItem) {
    if (this.parents == null) {
      this.parents = new ArrayList<TreeItemParent>();
    }
    this.parents.add(parentsItem);
    return this;
  }

   /**
   * Get parents
   * @return parents
  **/
  @ApiModelProperty(value = "")
  public List<TreeItemParent> getParents() {
    return parents;
  }

  public void setParents(List<TreeItemParent> parents) {
    this.parents = parents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreeItem treeItem = (TreeItem) o;
    return Objects.equals(this.parents, treeItem.parents) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parents, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreeItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    parents: ").append(toIndentedString(parents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

