/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.panda.sport.rcs.virtual.third.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.panda.sport.rcs.virtual.third.client.model.ReportParams;
import com.panda.sport.rcs.virtual.third.client.model.ReportTarget;
import java.io.IOException;

/**
 * Internal Turnover report parameters
 */
@ApiModel(description = "Internal Turnover report parameters")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-25T13:53:10.996Z")



public class TurnoverReportParams extends ReportParams {
  @SerializedName("includeDetails")
  private Boolean includeDetails = null;

  @SerializedName("produces")
  private String produces = "text/csv";

  @SerializedName("targetEntity")
  private Integer targetEntity = null;

  public TurnoverReportParams includeDetails(Boolean includeDetails) {
    this.includeDetails = includeDetails;
    return this;
  }

   /**
   * If enabled, report will incluide game details.
   * @return includeDetails
  **/
  @ApiModelProperty(value = "If enabled, report will incluide game details.")
  public Boolean isIncludeDetails() {
    return includeDetails;
  }

  public void setIncludeDetails(Boolean includeDetails) {
    this.includeDetails = includeDetails;
  }

  public TurnoverReportParams produces(String produces) {
    this.produces = produces;
    return this;
  }

   /**
   * Produces. 
   * @return produces
  **/
  @ApiModelProperty(required = true, value = "Produces. ")
  public String getProduces() {
    return produces;
  }

  public void setProduces(String produces) {
    this.produces = produces;
  }

  public TurnoverReportParams targetEntity(Integer targetEntity) {
    this.targetEntity = targetEntity;
    return this;
  }

   /**
   * Id of entity which represent the target entity. 
   * @return targetEntity
  **/
  @ApiModelProperty(required = true, value = "Id of entity which represent the target entity. ")
  public Integer getTargetEntity() {
    return targetEntity;
  }

  public void setTargetEntity(Integer targetEntity) {
    this.targetEntity = targetEntity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TurnoverReportParams turnoverReportParams = (TurnoverReportParams) o;
    return Objects.equals(this.includeDetails, turnoverReportParams.includeDetails) &&
        Objects.equals(this.produces, turnoverReportParams.produces) &&
        Objects.equals(this.targetEntity, turnoverReportParams.targetEntity) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeDetails, produces, targetEntity, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TurnoverReportParams {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    includeDetails: ").append(toIndentedString(includeDetails)).append("\n");
    sb.append("    produces: ").append(toIndentedString(produces)).append("\n");
    sb.append("    targetEntity: ").append(toIndentedString(targetEntity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

