/*
 * GoldenRace External API
 * Definitions of External API for GoldenRace Java Server 
 *
 * OpenAPI spec version: 7.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.test.api;

import com.panda.sport.rcs.virtual.third.client.model.Log;
import com.panda.sport.rcs.virtual.third.client.model.SessionLog;
import org.junit.Ignore;
import org.junit.Test;
import org.threeten.bp.OffsetDateTime;

import java.util.List;

/**
 * API tests for LogApi
 */
@Ignore
public class LogApiTest {

    private final com.panda.sport.rcs.virtual.third.client.api.LogApi api = new com.panda.sport.rcs.virtual.third.client.api.LogApi();

    
    /**
     * 
     *
     * Produces a history of logs 
     *
     * @throws com.panda.sport.rcs.virtual.third.client.ApiException
     *          if the Api call fails
     */
    @Test
    public void logFindTest() throws com.panda.sport.rcs.virtual.third.client.ApiException {
        Integer entityId = null;
        OffsetDateTime startTime = null;
        Integer n = null;
        Integer first = null;
        String orderBy = null;
        OffsetDateTime endTime = null;
        String type = null;
        String method = null;
        List<Integer> responseStatusCodes = null;
        List<String> ips = null;
        String description = null;
        Boolean withChildren = null;
        Boolean advancedInfo = null;
        List<Log> response = api.logFind(entityId, startTime, n, first, orderBy, endTime, type, method, responseStatusCodes, ips, description, withChildren, advancedInfo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Return a list of logs by transactionId 
     *
     * @throws com.panda.sport.rcs.virtual.third.client.ApiException
     *          if the Api call fails
     */
    @Test
    public void logFindByIdTest() throws com.panda.sport.rcs.virtual.third.client.ApiException {
        Integer entityId = null;
        String transactionId = null;
        Boolean withChildren = null;
        List<Log> response = api.logFindById(entityId, transactionId, withChildren);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieve the session logs of an entity and its children 
     *
     * @throws com.panda.sport.rcs.virtual.third.client.ApiException
     *          if the Api call fails
     */
    @Test
    public void logSessionFindTest() throws com.panda.sport.rcs.virtual.third.client.ApiException {
        Integer entityId = null;
        OffsetDateTime startTime = null;
        Integer n = null;
        String orderBy = null;
        OffsetDateTime endTime = null;
        Boolean withChildren = null;
        List<SessionLog> response = api.logSessionFind(entityId, startTime, n, orderBy, endTime, withChildren);

        // TODO: test validations
    }
    
}
